name: Build
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build and Unit Test
      run: zig build test -Doptimize=ReleaseSmall
